# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubeflare < Formula
  desc "Kubeflare is a utility to authenticate to Kubernetes clusters using Cloudflare Access"
  homepage "https://dev.shib.me/kubeflare"
  version "0.1.2"
  license "MIT"

  depends_on "cloudflared"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.2/kubeflare_darwin_amd64.zip"
      sha256 "a39c5dd08eae9a9f4aea206df6c0fe3095aad5bf9c46a8e792923e712dc08bdc"

      def install
        bin.install "kubeflare"
        generate_completions_from_executable(bin/"kubeflare","completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.2/kubeflare_darwin_arm64.zip"
      sha256 "3492730c40ffa84a959525576e11c2823bfa93b6b776446530dedd490ec60a73"

      def install
        bin.install "kubeflare"
        generate_completions_from_executable(bin/"kubeflare","completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.2/kubeflare_linux_amd64.zip"
      sha256 "97d4d103f3882d9a79f7da4a03c9c12521306e8d2127e2d1fd07312d2ff6b125"
      def install
        bin.install "kubeflare"
        generate_completions_from_executable(bin/"kubeflare","completion")
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.2/kubeflare_linux_arm.zip"
      sha256 "eb8149c572efc834002a83e524f0cb69a8568c97a6903cf7a075cddcbc7d8614"
      def install
        bin.install "kubeflare"
        generate_completions_from_executable(bin/"kubeflare","completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.2/kubeflare_linux_arm64.zip"
      sha256 "4bd3c84c3709e8ba50edac09999977b19daa40d2db84a2a1c98ef1ef9101e886"
      def install
        bin.install "kubeflare"
        generate_completions_from_executable(bin/"kubeflare","completion")
      end
    end
  end
end
