# This file was generated by GoReleaser. DO NOT EDIT.
cask "demo-cli" do
  name "demo-cli"
  desc ""
  homepage "https://github.com/shibme/demo-cli"
  version "0.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "demo-cli"

  on_macos do
    on_arm do
      url "https://github.com/shibme/demo-cli/releases/download/v#{version}/demo-cli_#{version}_darwin_arm64.zip"
      sha256 "375cd0b4d41805798bbc5f319d3d8d34810b1a45b710e1065107a8ae8549e484"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shibme/demo-cli/releases/download/v#{version}/demo-cli_#{version}_linux_arm64.zip"
      sha256 "b55e085f35d5b031f0fa8bd46e94273aa41ff85869c31b67fedeb08028ddae7e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/demo-cli"]
    end
  end

  # No zap stanza required
end
