# This file was generated by GoReleaser. DO NOT EDIT.
cask "demo-cli" do
  name "demo-cli"
  desc ""
  homepage "https://github.com/shibme/demo-cli"
  version "0.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "demo-cli"

  on_macos do
    on_arm do
      url "https://github.com/shibme/demo-cli/releases/download/v#{version}/demo-cli_#{version}_darwin_arm64.zip"
      sha256 "5776df43788f3de0f0995b10b83fe0ece437f86960784022447c8664edac7155"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/shibme/demo-cli/releases/download/v#{version}/demo-cli_#{version}_linux_arm64.zip"
      sha256 "f974fb6ae75b12f8798c0aaacde2b354af51a6a5634f32252bfc62f1ba9a9615"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/demo-cli"]
    end
  end

  # No zap stanza required
end
