# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubeflare" do
  desc "Kubeflare is a utility to authenticate to Kubernetes clusters using Cloudflare Access"
  homepage "https://dev.shib.me/kubeflare"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubeflare"
  bash_completion "kubeflare completion bash > /usr/local/etc/bash_completion.d/kubeflare
"
  zsh_completion "kubeflare completion zsh > /usr/local/share/zsh/site-functions/_kubeflare
"
  fish_completion "kubeflare completion fish > /usr/local/share/fish/vendor_completions.d/kubeflare.fish
"
  depends_on formula: [
      "cloudflared",
    ]

  on_macos do
    on_intel do
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.1/kubeflare_darwin_amd64.zip"
      sha256 "7f64f8e8fd37556f6eae0e99ab34ec362a91f87d30757217d75dfa8f2f48ba81"
    end
    on_arm do
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.1/kubeflare_darwin_arm64.zip"
      sha256 "6f1443a61d81406ee2c71fc3c50547dcb1cfc63b57655aac6bf790a9a36ed779"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.1/kubeflare_linux_amd64.zip"
      sha256 "2f103b9f4375f23f7776e44d36c854ad2a5bd27d8b78d5996a05d2dafe6e5eff"
    end
    on_arm do
      url "https://github.com/shibme/kubeflare/releases/download/v0.1.1/kubeflare_linux_arm64.zip"
      sha256 "282a1a470ad6fff2e18d309c647b8bf79e7af41732e70fb4823454414817f27a"
    end
  end

  # No zap stanza required
end
